/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rc_loveq_patchupdatedemo_utils_PatchUtils */

#ifndef _Included_rc_loveq_patchupdatedemo_utils_PatchUtils
#define _Included_rc_loveq_patchupdatedemo_utils_PatchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rc_loveq_patchupdatedemo_utils_PatchUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_rc_loveq_patchupdatedemo_utils_PatchUtils_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
